# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YuYzYba2Ws1igCAfYDA72LGotjsA7_bQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile devsecops.yml
# name: DevSecOps Secure CI/CD Pipeline
# 
# on:
#   push:
#     branches: [ "main", "develop" ]
# # ... rest of your pipeline code ...

!cat devsecops.yml